/**
 * Percentile comparisons for the stats pane.
 *
 * The topbar's five ratios compare themselves against `CLEAR_CORPUS`; the tool
 * statistics do the same here from `CLEAR_STAT_NORMS`, which is generated by
 * running the tools themselves over the same corpus. Only rates and scores have
 * norms — a raw count has no meaningful place in a ~174-word excerpt — so
 * `compareStat` returns `undefined` for anything without one and the chip simply
 * does not render.
 *
 * The percentile is the value's own rank in the corpus. Its *colour* follows
 * difficulty instead, which is the topbar's convention, so Flesch Reading Ease
 * (where a high score is easy) is marked `higherIsEasier` and its tint flips
 * while the number does not.
 */
import { CLEAR_STAT_NORMS } from './data/stat-norms';
import { describeNorm, percentileFromZ, zScore } from './metrics';
import type { StatComparison } from './types';

/** Stats where the *low* end is the hard end. */
const HIGHER_IS_EASIER = new Set(['read.flesch']);

/** Stats stored as 0–1 fractions, formatted as percentages in the tooltip. */
const FRACTIONS = new Set(['read.complex.share']);

export function compareStat(statId: string, value: number, label: string): StatComparison | undefined {
  const norm = CLEAR_STAT_NORMS.metrics[statId];
  if (!norm) return undefined;
  const z = zScore(value, norm);
  if (z === null) return undefined;

  return {
    percentile: percentileFromZ(z),
    z,
    higherIsEasier: HIGHER_IS_EASIER.has(statId) || undefined,
    description: `${label}: CLEAR corpus, ${describeNorm(norm, {
      n: CLEAR_STAT_NORMS.n,
      percent: FRACTIONS.has(statId),
    })}`,
  };
}
